print("Hello World")
print("Hoy")
print("Goodbye World")
print("Goy")
print("Salutations World")
print("Soy")
print("Farewell World")
print("Foy")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")
print("Bonjour World")